### ISSUE TITLE
Adding HAS_ROOT guard to source/srs/analysis/DataWriter.hpp

### ISSUE THREAD

**Issue by kLayz3** [YanzhaoW/srs-daq#1]
Hey Yanzhao,

for the build, having ROOT is optional (stated in README), however it doesn't compile.

There are `HAS_ROOT` guards missing in the header file:
source/srs/analysis/DataWriter.hpp

, akin to source/srs/analysis/DataWriter.cpp

Could you add the guard around 
`class RootFileSink;` (line 11)
'std::unique_ptr<RootFileSink> root_file_;' (line 46)

Cheers,
-- Martin

**Comment by YanzhaoW** [comment]
Hi, Martin.

Thanks for this information. Yeah, I haven't test out compiling and running with ROOT, I will fix this and update it later today.

**Comment by YanzhaoW** [comment]
Hi, Martin

I have pushed the update to the dev branch and tested the program locally without ROOT dep.

I also updated the readme, where you can see an option to forcedly disable ROOT dep with a CMake option.

If you need something else, please let me know.
